### ISSUE TITLE
Cinnamon 2.3 develop disconnects (FRC)

### ISSUE THREAD

**Issue by rchastain** [gekomad/Cinnamon#49]
Hello!
I tested the develop branch in a CuteChess tournament. There is still a problem. Here is a position on which the engine disconnects.
```
Started game 1 of 4 (Cinnamon 2.3 vs Sjaak 524)
22 >Cinnamon 2.3(0): setoption name UCI_Chess960 value true
22 >Cinnamon 2.3(0): ucinewgame
22 >Cinnamon 2.3(0): setoption name Ponder value false
22 >Cinnamon 2.3(0): position fen rkrnbnqb/pppppppp/8/8/8/8/PPPPPPPP/RKRNBNQB w CAca - 0 1

37315 >Cinnamon 2.3(0): position fen rkrnbnqb/pppppppp/8/8/8/8/PPPPPPPP/RKRNBNQB w CAca - 0 1 moves d1c3 g7g5 d2d3 f7f5 g2g4 f5g4 g1g4 f8e6 f1g3 g8f7 g3f5 h8e5 c3d5 d8c6 g4f3 c6d4 f5d4 e6d4 f3e4 d4c6 e1d2 f7g7 d2c3 e8g6 c3e5 c6e5 e4b4 e5c6 b4g4 e7e6 d5e3 b8c8 g4g5 f8f2
37315 >Cinnamon 2.3(0): isready
37315 <Cinnamon 2.3(0): fenStr: f8f2 from: 58
37315 <Cinnamon 2.3(0): Wed Oct 21 21:37:47 2020 ********************************** assert error in GenMoves.cpp:539  **********************************
```

The same command in _Alouette_:
```
Alouette 0.1.3
setoption name UCI_Chess960 value true
position fen rkrnbnqb/pppppppp/8/8/8/8/PPPPPPPP/RKRNBNQB w CAca - 0 1 moves d1c3 g7g5 d2d3 f7f5 g2g4 f5g4 g1g4 f8e6 f1g3 g8f7 g3f5 h8e5 c3d5 d8c6 g4f3 c6d4 f5d4 e6d4 f3e4 d4c6 e1d2 f7g7 d2c3 e8g6 c3e5 c6e5 e4b4 e5c6 b4g4 e7e6 d5e3 b8c8 g4g5 f8f2
show
+  A B C D E F G H  +
8 |r|:|.|:|.|:|k|:| 8
7 |p|p|p|p|:|.|q|p| 7
6 |.|:|n|:|p|:|b|:| 6
5 |:|.|:|.|:|.|Q|.| 5
4 |.|:|.|:|.|:|.|:| 4
3 |:|.|:|P|N|.|:|.| 3
2 |P|P|P|:|P|r|.|P| 2
1 |R|K|R|.|:|.|:|B| 1
+  A B C D E F G H  + <--
Castling: CA
En passant: -
FEN: r5k1/pppp2qp/2n1p1b1/6Q1/8/3PN3/PPP1Pr1P/RKR4B w CA -
perft 1
Depth   Result   Time elapsed
    1       44   00:00:00:000
```
![cinnamon23-disconnects-202010212149](https://user-images.githubusercontent.com/13957204/96776009-af573300-13e8-11eb-8a6d-0817fb87b106.png)

Regards.
Roland

**Comment by gekomad** [comment]
Fixed! thanks

**Comment by rchastain** [comment]
> Fixed! thanks

You're welcome. I will test it ASAP.

**Comment by rchastain** [comment]
Made another test with the code from the _develop_ branch. There is still a problem. The engine disconnects after this line:

```
position fen rqbknbnr/pppppppp/8/8/8/8/PPPPPPPP/RQBKNBNR w HAha - 0 1 moves g1f3 d7d5 d2d4 e8d6 c1f4 g7g6 f4d6 c7d6 e2e3 f8g7 f3g5 g8h6 f1e2 d8h8 e1d3 e7e5 d3b4 f7f6 g5f3 c8e6 f3d2 e5d4 e3d4 h6f5 c2c3 g7h6 h1e1 a7a5 b4d3 b8c7 b1c2 f8c8 
```

And before that, there is a problem with the command **setoption**:

```
235713 >Cinnamon 2.3(2): setoption name UCI_Chess960 value true
235713 >Cinnamon 2.3(2): ucinewgame
235713 >Cinnamon 2.3(2): setoption name Ponder value false
235713 >Cinnamon 2.3(2): position fen rqbknbnr/pppppppp/8/8/8/8/PPPPPPPP/RQBKNBNR w HAha - 0 1
235713 >Cinnamon 2.3(2): isready
235714 <Cinnamon 2.3(2): Unknown command: setoption name UCI_Chess960 value true
235714 <Cinnamon 2.3(2): Unknown command: setoption name Ponder value false
```

**Comment by gekomad** [comment]
I did a lot of matches with cutechess-cli and that problem didn't occur. There seems there is a space after f8c8, are you using cutechess-cli?

Anyway get the last version f05771b16b776aabdd5998bae0595f14f20fe425 
thanks

**Comment by gekomad** [comment]
I've trimmed the command, new commit f41f3b4a27eb661044a4d1627c6675318b29dacc

**Comment by rchastain** [comment]
I have just made another test with the latest code from the _develop_ branch. The result is the same.

```
setoption name UCI_Chess960 value true
Unknown command: setoption name UCI_Chess960 value true
position fen rqbknbnr/pppppppp/8/8/8/8/PPPPPPPP/RQBKNBNR w HAha - 0 1 moves g1f3 d7d5 d2d4 e8d6 c1f4 g7g6 f4d6 c7d6 e2e3 f8g7 f3g5 g8h6 f1e2 d8h8 e1d3 e7e5 d3b4 f7f6 g5f3 c8e6 f3d2 e5d4 e3d4 h6f5 c2c3 g7h6 h1e1 a7a5 b4d3 b8c7 b1c2 f8c8
fenStr: f8c8 from: 58

Sun Oct 25 21:53:58 2020 ********************************** assert error in GenMoves.cpp:539  **********************************
[roland@localhost src (master)]$ 
```
I didn't use CuteChess. I just opened a terminal, ran Cinnamon and entered that two commands (`setoption` and `position`).

**Comment by gekomad** [comment]
Are you using develop branch? that error should be at line 506

**Comment by rchastain** [comment]
> Are you using develop branch? that error should be at line 506

Yes, I believe. But I will check.

**Comment by rchastain** [comment]
Still the same problem. I don't understand what happens. I selected the _develop_ branch, cloned the repository, built cinnamon with `make cinnamon64-generic`. And I still get the same error...

**Comment by rchastain** [comment]
I downloaded a ZIP (instead of cloning) and now it works: no more error. It seems that copying the url from the green button always give the adress of the _master_ branch.
So you can close the issue. Good job! And sorry for the wrong bug report. :)

**Comment by gekomad** [comment]
did you run 'git pull' on develop branch?

**Comment by rchastain** [comment]
> did you run 'git pull' on develop branch?

No, I just made `git clone` with the adress copied from the green button. See my previous message.
Is it necessary to pull?

**Comment by gekomad** [comment]
after clone switch to develop branch with `git checkout develop`

**Comment by rchastain** [comment]
OK, thank you, I didn't know.
Have a nice day!
Regards.
Roland
